import React from "react";
import "./index.css";
import ReactDOM from "react-dom/client";
import { makePersistedAdapter } from "@livestore/adapter-web";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { LiveStoreProvider } from "@livestore/react";
// This file is generated by the plugin:
import { routeTree } from "./routeTree.gen";
import { schema } from "./livestore/schema";
import { BookSpinner } from "./components/BookSpinner";
import { authClient } from "./lib/auth-client";

import LiveStoreWorker from "./livestore/livestore.worker?worker";
import LiveStoreSharedWorker from "@livestore/adapter-web/shared-worker?sharedworker";

import { unstable_batchedUpdates as batchUpdates } from "react-dom";

const router = createRouter({ routeTree });
const qc = new QueryClient();

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

function App() {
  const { data: session, isPending } = authClient.useSession();

  if (isPending) {
    // Still checking session — show a minimal loading state
    return (
      <div className="flex min-h-screen items-center justify-center">
        <BookSpinner />
      </div>
    );
  }

  if (!session) {
    // No session — render the router without LiveStore so /login and /register work
    return (
      <QueryClientProvider client={qc}>
        <RouterProvider router={router} />
      </QueryClientProvider>
    );
  }

  // Authenticated — create a per-user adapter so each user gets their own store
  const adapter = makePersistedAdapter({
    storage: { type: "opfs" },
    worker: LiveStoreWorker,
    sharedWorker: LiveStoreSharedWorker,
  });

  return (
    <LiveStoreProvider
      schema={schema}
      adapter={adapter}
      storeId={session.user.id}
      syncPayload={{
        authToken: session.session.token,
        storeId: session.user.id,
      }}
      batchUpdates={batchUpdates}
      renderLoading={() => (
        <div className="flex min-h-screen items-center justify-center">
          <BookSpinner />
        </div>
      )}
    >
      <QueryClientProvider client={qc}>
        <RouterProvider router={router} />
      </QueryClientProvider>
    </LiveStoreProvider>
  );
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
