import React from 'react'
import "./index.css"
import ReactDOM from 'react-dom/client'
import LiveStoreSharedWorker from '@livestore/adapter-web/shared-worker?sharedworker'
import { makePersistedAdapter } from '@livestore/adapter-web'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { LiveStoreProvider } from '@livestore/react'
// This file is generated by the plugin:
import { routeTree } from './routeTree.gen'
import { schema } from './livestore/schema'

import LiveStoreWorker from './livestore.worker?worker'

import { unstable_batchedUpdates as batchUpdates } from 'react-dom'

const router = createRouter({ routeTree })
const qc = new QueryClient()

declare module '@tanstack/react-router' {
  interface Register { router: typeof router }
}
const adapter = makePersistedAdapter({
  storage: { type: 'opfs' },
  worker: LiveStoreWorker,
  sharedWorker: LiveStoreSharedWorker,
})
ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <LiveStoreProvider schema={schema} adapter={adapter} batchUpdates={batchUpdates}>
      <QueryClientProvider client={qc}>
        <RouterProvider router={router} />
      </QueryClientProvider>
    </LiveStoreProvider>
  </React.StrictMode>
)
