/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BooksRouteRouteImport } from './routes/books.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksNewRouteImport } from './routes/books.new'
import { Route as BooksListRouteImport } from './routes/books.list'
import { Route as BooksBookIdRouteRouteImport } from './routes/books.$bookId.route'
import { Route as BooksBookIdIndexRouteImport } from './routes/books.$bookId.index'
import { Route as BooksBookIdNotesRouteRouteImport } from './routes/books.$bookId.notes.route'
import { Route as BooksBookIdNotesIndexRouteImport } from './routes/books.$bookId.notes.index'
import { Route as BooksBookIdNotesNewRouteImport } from './routes/books.$bookId.notes.new'
import { Route as BooksBookIdNotesNoteIdRouteImport } from './routes/books.$bookId.notes.$noteId'
import { Route as BooksBookIdNotesRelationshipsNewRouteImport } from './routes/books.$bookId.notes.relationships.new'

const BooksRouteRoute = BooksRouteRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksNewRoute = BooksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BooksRouteRoute,
} as any)
const BooksListRoute = BooksListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => BooksRouteRoute,
} as any)
const BooksBookIdRouteRoute = BooksBookIdRouteRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRouteRoute,
} as any)
const BooksBookIdIndexRoute = BooksBookIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksBookIdRouteRoute,
} as any)
const BooksBookIdNotesRouteRoute = BooksBookIdNotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => BooksBookIdRouteRoute,
} as any)
const BooksBookIdNotesIndexRoute = BooksBookIdNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksBookIdNotesRouteRoute,
} as any)
const BooksBookIdNotesNewRoute = BooksBookIdNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BooksBookIdNotesRouteRoute,
} as any)
const BooksBookIdNotesNoteIdRoute = BooksBookIdNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => BooksBookIdNotesRouteRoute,
} as any)
const BooksBookIdNotesRelationshipsNewRoute =
  BooksBookIdNotesRelationshipsNewRouteImport.update({
    id: '/relationships/new',
    path: '/relationships/new',
    getParentRoute: () => BooksBookIdNotesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRouteRouteWithChildren
  '/books/list': typeof BooksListRoute
  '/books/new': typeof BooksNewRoute
  '/books/$bookId/notes': typeof BooksBookIdNotesRouteRouteWithChildren
  '/books/$bookId/': typeof BooksBookIdIndexRoute
  '/books/$bookId/notes/$noteId': typeof BooksBookIdNotesNoteIdRoute
  '/books/$bookId/notes/new': typeof BooksBookIdNotesNewRoute
  '/books/$bookId/notes/': typeof BooksBookIdNotesIndexRoute
  '/books/$bookId/notes/relationships/new': typeof BooksBookIdNotesRelationshipsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteRouteWithChildren
  '/books/list': typeof BooksListRoute
  '/books/new': typeof BooksNewRoute
  '/books/$bookId': typeof BooksBookIdIndexRoute
  '/books/$bookId/notes/$noteId': typeof BooksBookIdNotesNoteIdRoute
  '/books/$bookId/notes/new': typeof BooksBookIdNotesNewRoute
  '/books/$bookId/notes': typeof BooksBookIdNotesIndexRoute
  '/books/$bookId/notes/relationships/new': typeof BooksBookIdNotesRelationshipsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRouteRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRouteRouteWithChildren
  '/books/list': typeof BooksListRoute
  '/books/new': typeof BooksNewRoute
  '/books/$bookId/notes': typeof BooksBookIdNotesRouteRouteWithChildren
  '/books/$bookId/': typeof BooksBookIdIndexRoute
  '/books/$bookId/notes/$noteId': typeof BooksBookIdNotesNoteIdRoute
  '/books/$bookId/notes/new': typeof BooksBookIdNotesNewRoute
  '/books/$bookId/notes/': typeof BooksBookIdNotesIndexRoute
  '/books/$bookId/notes/relationships/new': typeof BooksBookIdNotesRelationshipsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/books/$bookId'
    | '/books/list'
    | '/books/new'
    | '/books/$bookId/notes'
    | '/books/$bookId/'
    | '/books/$bookId/notes/$noteId'
    | '/books/$bookId/notes/new'
    | '/books/$bookId/notes/'
    | '/books/$bookId/notes/relationships/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/books/list'
    | '/books/new'
    | '/books/$bookId'
    | '/books/$bookId/notes/$noteId'
    | '/books/$bookId/notes/new'
    | '/books/$bookId/notes'
    | '/books/$bookId/notes/relationships/new'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/books/$bookId'
    | '/books/list'
    | '/books/new'
    | '/books/$bookId/notes'
    | '/books/$bookId/'
    | '/books/$bookId/notes/$noteId'
    | '/books/$bookId/notes/new'
    | '/books/$bookId/notes/'
    | '/books/$bookId/notes/relationships/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRouteRoute: typeof BooksRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/new': {
      id: '/books/new'
      path: '/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof BooksNewRouteImport
      parentRoute: typeof BooksRouteRoute
    }
    '/books/list': {
      id: '/books/list'
      path: '/list'
      fullPath: '/books/list'
      preLoaderRoute: typeof BooksListRouteImport
      parentRoute: typeof BooksRouteRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteRouteImport
      parentRoute: typeof BooksRouteRoute
    }
    '/books/$bookId/': {
      id: '/books/$bookId/'
      path: '/'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof BooksBookIdIndexRouteImport
      parentRoute: typeof BooksBookIdRouteRoute
    }
    '/books/$bookId/notes': {
      id: '/books/$bookId/notes'
      path: '/notes'
      fullPath: '/books/$bookId/notes'
      preLoaderRoute: typeof BooksBookIdNotesRouteRouteImport
      parentRoute: typeof BooksBookIdRouteRoute
    }
    '/books/$bookId/notes/': {
      id: '/books/$bookId/notes/'
      path: '/'
      fullPath: '/books/$bookId/notes/'
      preLoaderRoute: typeof BooksBookIdNotesIndexRouteImport
      parentRoute: typeof BooksBookIdNotesRouteRoute
    }
    '/books/$bookId/notes/new': {
      id: '/books/$bookId/notes/new'
      path: '/new'
      fullPath: '/books/$bookId/notes/new'
      preLoaderRoute: typeof BooksBookIdNotesNewRouteImport
      parentRoute: typeof BooksBookIdNotesRouteRoute
    }
    '/books/$bookId/notes/$noteId': {
      id: '/books/$bookId/notes/$noteId'
      path: '/$noteId'
      fullPath: '/books/$bookId/notes/$noteId'
      preLoaderRoute: typeof BooksBookIdNotesNoteIdRouteImport
      parentRoute: typeof BooksBookIdNotesRouteRoute
    }
    '/books/$bookId/notes/relationships/new': {
      id: '/books/$bookId/notes/relationships/new'
      path: '/relationships/new'
      fullPath: '/books/$bookId/notes/relationships/new'
      preLoaderRoute: typeof BooksBookIdNotesRelationshipsNewRouteImport
      parentRoute: typeof BooksBookIdNotesRouteRoute
    }
  }
}

interface BooksBookIdNotesRouteRouteChildren {
  BooksBookIdNotesNoteIdRoute: typeof BooksBookIdNotesNoteIdRoute
  BooksBookIdNotesNewRoute: typeof BooksBookIdNotesNewRoute
  BooksBookIdNotesIndexRoute: typeof BooksBookIdNotesIndexRoute
  BooksBookIdNotesRelationshipsNewRoute: typeof BooksBookIdNotesRelationshipsNewRoute
}

const BooksBookIdNotesRouteRouteChildren: BooksBookIdNotesRouteRouteChildren = {
  BooksBookIdNotesNoteIdRoute: BooksBookIdNotesNoteIdRoute,
  BooksBookIdNotesNewRoute: BooksBookIdNotesNewRoute,
  BooksBookIdNotesIndexRoute: BooksBookIdNotesIndexRoute,
  BooksBookIdNotesRelationshipsNewRoute: BooksBookIdNotesRelationshipsNewRoute,
}

const BooksBookIdNotesRouteRouteWithChildren =
  BooksBookIdNotesRouteRoute._addFileChildren(
    BooksBookIdNotesRouteRouteChildren,
  )

interface BooksBookIdRouteRouteChildren {
  BooksBookIdNotesRouteRoute: typeof BooksBookIdNotesRouteRouteWithChildren
  BooksBookIdIndexRoute: typeof BooksBookIdIndexRoute
}

const BooksBookIdRouteRouteChildren: BooksBookIdRouteRouteChildren = {
  BooksBookIdNotesRouteRoute: BooksBookIdNotesRouteRouteWithChildren,
  BooksBookIdIndexRoute: BooksBookIdIndexRoute,
}

const BooksBookIdRouteRouteWithChildren =
  BooksBookIdRouteRoute._addFileChildren(BooksBookIdRouteRouteChildren)

interface BooksRouteRouteChildren {
  BooksBookIdRouteRoute: typeof BooksBookIdRouteRouteWithChildren
  BooksListRoute: typeof BooksListRoute
  BooksNewRoute: typeof BooksNewRoute
}

const BooksRouteRouteChildren: BooksRouteRouteChildren = {
  BooksBookIdRouteRoute: BooksBookIdRouteRouteWithChildren,
  BooksListRoute: BooksListRoute,
  BooksNewRoute: BooksNewRoute,
}

const BooksRouteRouteWithChildren = BooksRouteRoute._addFileChildren(
  BooksRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRouteRoute: BooksRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
