/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBooksRouteRouteImport } from './routes/_authenticated.books.route'
import { Route as AuthenticatedBooksNewRouteImport } from './routes/_authenticated.books.new'
import { Route as AuthenticatedBooksListRouteImport } from './routes/_authenticated.books.list'
import { Route as AuthenticatedBooksBookIdRouteRouteImport } from './routes/_authenticated.books.$bookId.route'
import { Route as AuthenticatedBooksBookIdIndexRouteImport } from './routes/_authenticated.books.$bookId.index'
import { Route as AuthenticatedBooksBookIdGraphRouteImport } from './routes/_authenticated.books.$bookId.graph'
import { Route as AuthenticatedBooksBookIdNotesRouteRouteImport } from './routes/_authenticated.books.$bookId.notes.route'
import { Route as AuthenticatedBooksBookIdNotesIndexRouteImport } from './routes/_authenticated.books.$bookId.notes.index'
import { Route as AuthenticatedBooksBookIdNotesNewRouteImport } from './routes/_authenticated.books.$bookId.notes.new'
import { Route as AuthenticatedBooksBookIdNotesNoteIdRouteImport } from './routes/_authenticated.books.$bookId.notes.$noteId'
import { Route as AuthenticatedBooksBookIdNotesRelationshipsNewRouteImport } from './routes/_authenticated.books.$bookId.notes.relationships.new'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBooksRouteRoute = AuthenticatedBooksRouteRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBooksNewRoute = AuthenticatedBooksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBooksRouteRoute,
} as any)
const AuthenticatedBooksListRoute = AuthenticatedBooksListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthenticatedBooksRouteRoute,
} as any)
const AuthenticatedBooksBookIdRouteRoute =
  AuthenticatedBooksBookIdRouteRouteImport.update({
    id: '/$bookId',
    path: '/$bookId',
    getParentRoute: () => AuthenticatedBooksRouteRoute,
  } as any)
const AuthenticatedBooksBookIdIndexRoute =
  AuthenticatedBooksBookIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBooksBookIdRouteRoute,
  } as any)
const AuthenticatedBooksBookIdGraphRoute =
  AuthenticatedBooksBookIdGraphRouteImport.update({
    id: '/graph',
    path: '/graph',
    getParentRoute: () => AuthenticatedBooksBookIdRouteRoute,
  } as any)
const AuthenticatedBooksBookIdNotesRouteRoute =
  AuthenticatedBooksBookIdNotesRouteRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedBooksBookIdRouteRoute,
  } as any)
const AuthenticatedBooksBookIdNotesIndexRoute =
  AuthenticatedBooksBookIdNotesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBooksBookIdNotesRouteRoute,
  } as any)
const AuthenticatedBooksBookIdNotesNewRoute =
  AuthenticatedBooksBookIdNotesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedBooksBookIdNotesRouteRoute,
  } as any)
const AuthenticatedBooksBookIdNotesNoteIdRoute =
  AuthenticatedBooksBookIdNotesNoteIdRouteImport.update({
    id: '/$noteId',
    path: '/$noteId',
    getParentRoute: () => AuthenticatedBooksBookIdNotesRouteRoute,
  } as any)
const AuthenticatedBooksBookIdNotesRelationshipsNewRoute =
  AuthenticatedBooksBookIdNotesRelationshipsNewRouteImport.update({
    id: '/relationships/new',
    path: '/relationships/new',
    getParentRoute: () => AuthenticatedBooksBookIdNotesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/books': typeof AuthenticatedBooksRouteRouteWithChildren
  '/books/$bookId': typeof AuthenticatedBooksBookIdRouteRouteWithChildren
  '/books/list': typeof AuthenticatedBooksListRoute
  '/books/new': typeof AuthenticatedBooksNewRoute
  '/books/$bookId/notes': typeof AuthenticatedBooksBookIdNotesRouteRouteWithChildren
  '/books/$bookId/graph': typeof AuthenticatedBooksBookIdGraphRoute
  '/books/$bookId/': typeof AuthenticatedBooksBookIdIndexRoute
  '/books/$bookId/notes/$noteId': typeof AuthenticatedBooksBookIdNotesNoteIdRoute
  '/books/$bookId/notes/new': typeof AuthenticatedBooksBookIdNotesNewRoute
  '/books/$bookId/notes/': typeof AuthenticatedBooksBookIdNotesIndexRoute
  '/books/$bookId/notes/relationships/new': typeof AuthenticatedBooksBookIdNotesRelationshipsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/books': typeof AuthenticatedBooksRouteRouteWithChildren
  '/books/list': typeof AuthenticatedBooksListRoute
  '/books/new': typeof AuthenticatedBooksNewRoute
  '/books/$bookId/graph': typeof AuthenticatedBooksBookIdGraphRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdIndexRoute
  '/books/$bookId/notes/$noteId': typeof AuthenticatedBooksBookIdNotesNoteIdRoute
  '/books/$bookId/notes/new': typeof AuthenticatedBooksBookIdNotesNewRoute
  '/books/$bookId/notes': typeof AuthenticatedBooksBookIdNotesIndexRoute
  '/books/$bookId/notes/relationships/new': typeof AuthenticatedBooksBookIdNotesRelationshipsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/books': typeof AuthenticatedBooksRouteRouteWithChildren
  '/_authenticated/books/$bookId': typeof AuthenticatedBooksBookIdRouteRouteWithChildren
  '/_authenticated/books/list': typeof AuthenticatedBooksListRoute
  '/_authenticated/books/new': typeof AuthenticatedBooksNewRoute
  '/_authenticated/books/$bookId/notes': typeof AuthenticatedBooksBookIdNotesRouteRouteWithChildren
  '/_authenticated/books/$bookId/graph': typeof AuthenticatedBooksBookIdGraphRoute
  '/_authenticated/books/$bookId/': typeof AuthenticatedBooksBookIdIndexRoute
  '/_authenticated/books/$bookId/notes/$noteId': typeof AuthenticatedBooksBookIdNotesNoteIdRoute
  '/_authenticated/books/$bookId/notes/new': typeof AuthenticatedBooksBookIdNotesNewRoute
  '/_authenticated/books/$bookId/notes/': typeof AuthenticatedBooksBookIdNotesIndexRoute
  '/_authenticated/books/$bookId/notes/relationships/new': typeof AuthenticatedBooksBookIdNotesRelationshipsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/books'
    | '/books/$bookId'
    | '/books/list'
    | '/books/new'
    | '/books/$bookId/notes'
    | '/books/$bookId/graph'
    | '/books/$bookId/'
    | '/books/$bookId/notes/$noteId'
    | '/books/$bookId/notes/new'
    | '/books/$bookId/notes/'
    | '/books/$bookId/notes/relationships/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/books'
    | '/books/list'
    | '/books/new'
    | '/books/$bookId/graph'
    | '/books/$bookId'
    | '/books/$bookId/notes/$noteId'
    | '/books/$bookId/notes/new'
    | '/books/$bookId/notes'
    | '/books/$bookId/notes/relationships/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/books'
    | '/_authenticated/books/$bookId'
    | '/_authenticated/books/list'
    | '/_authenticated/books/new'
    | '/_authenticated/books/$bookId/notes'
    | '/_authenticated/books/$bookId/graph'
    | '/_authenticated/books/$bookId/'
    | '/_authenticated/books/$bookId/notes/$noteId'
    | '/_authenticated/books/$bookId/notes/new'
    | '/_authenticated/books/$bookId/notes/'
    | '/_authenticated/books/$bookId/notes/relationships/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/books': {
      id: '/_authenticated/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthenticatedBooksRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/books/new': {
      id: '/_authenticated/books/new'
      path: '/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AuthenticatedBooksNewRouteImport
      parentRoute: typeof AuthenticatedBooksRouteRoute
    }
    '/_authenticated/books/list': {
      id: '/_authenticated/books/list'
      path: '/list'
      fullPath: '/books/list'
      preLoaderRoute: typeof AuthenticatedBooksListRouteImport
      parentRoute: typeof AuthenticatedBooksRouteRoute
    }
    '/_authenticated/books/$bookId': {
      id: '/_authenticated/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdRouteRouteImport
      parentRoute: typeof AuthenticatedBooksRouteRoute
    }
    '/_authenticated/books/$bookId/': {
      id: '/_authenticated/books/$bookId/'
      path: '/'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof AuthenticatedBooksBookIdIndexRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRouteRoute
    }
    '/_authenticated/books/$bookId/graph': {
      id: '/_authenticated/books/$bookId/graph'
      path: '/graph'
      fullPath: '/books/$bookId/graph'
      preLoaderRoute: typeof AuthenticatedBooksBookIdGraphRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRouteRoute
    }
    '/_authenticated/books/$bookId/notes': {
      id: '/_authenticated/books/$bookId/notes'
      path: '/notes'
      fullPath: '/books/$bookId/notes'
      preLoaderRoute: typeof AuthenticatedBooksBookIdNotesRouteRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdRouteRoute
    }
    '/_authenticated/books/$bookId/notes/': {
      id: '/_authenticated/books/$bookId/notes/'
      path: '/'
      fullPath: '/books/$bookId/notes/'
      preLoaderRoute: typeof AuthenticatedBooksBookIdNotesIndexRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdNotesRouteRoute
    }
    '/_authenticated/books/$bookId/notes/new': {
      id: '/_authenticated/books/$bookId/notes/new'
      path: '/new'
      fullPath: '/books/$bookId/notes/new'
      preLoaderRoute: typeof AuthenticatedBooksBookIdNotesNewRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdNotesRouteRoute
    }
    '/_authenticated/books/$bookId/notes/$noteId': {
      id: '/_authenticated/books/$bookId/notes/$noteId'
      path: '/$noteId'
      fullPath: '/books/$bookId/notes/$noteId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdNotesRouteRoute
    }
    '/_authenticated/books/$bookId/notes/relationships/new': {
      id: '/_authenticated/books/$bookId/notes/relationships/new'
      path: '/relationships/new'
      fullPath: '/books/$bookId/notes/relationships/new'
      preLoaderRoute: typeof AuthenticatedBooksBookIdNotesRelationshipsNewRouteImport
      parentRoute: typeof AuthenticatedBooksBookIdNotesRouteRoute
    }
  }
}

interface AuthenticatedBooksBookIdNotesRouteRouteChildren {
  AuthenticatedBooksBookIdNotesNoteIdRoute: typeof AuthenticatedBooksBookIdNotesNoteIdRoute
  AuthenticatedBooksBookIdNotesNewRoute: typeof AuthenticatedBooksBookIdNotesNewRoute
  AuthenticatedBooksBookIdNotesIndexRoute: typeof AuthenticatedBooksBookIdNotesIndexRoute
  AuthenticatedBooksBookIdNotesRelationshipsNewRoute: typeof AuthenticatedBooksBookIdNotesRelationshipsNewRoute
}

const AuthenticatedBooksBookIdNotesRouteRouteChildren: AuthenticatedBooksBookIdNotesRouteRouteChildren =
  {
    AuthenticatedBooksBookIdNotesNoteIdRoute:
      AuthenticatedBooksBookIdNotesNoteIdRoute,
    AuthenticatedBooksBookIdNotesNewRoute:
      AuthenticatedBooksBookIdNotesNewRoute,
    AuthenticatedBooksBookIdNotesIndexRoute:
      AuthenticatedBooksBookIdNotesIndexRoute,
    AuthenticatedBooksBookIdNotesRelationshipsNewRoute:
      AuthenticatedBooksBookIdNotesRelationshipsNewRoute,
  }

const AuthenticatedBooksBookIdNotesRouteRouteWithChildren =
  AuthenticatedBooksBookIdNotesRouteRoute._addFileChildren(
    AuthenticatedBooksBookIdNotesRouteRouteChildren,
  )

interface AuthenticatedBooksBookIdRouteRouteChildren {
  AuthenticatedBooksBookIdNotesRouteRoute: typeof AuthenticatedBooksBookIdNotesRouteRouteWithChildren
  AuthenticatedBooksBookIdGraphRoute: typeof AuthenticatedBooksBookIdGraphRoute
  AuthenticatedBooksBookIdIndexRoute: typeof AuthenticatedBooksBookIdIndexRoute
}

const AuthenticatedBooksBookIdRouteRouteChildren: AuthenticatedBooksBookIdRouteRouteChildren =
  {
    AuthenticatedBooksBookIdNotesRouteRoute:
      AuthenticatedBooksBookIdNotesRouteRouteWithChildren,
    AuthenticatedBooksBookIdGraphRoute: AuthenticatedBooksBookIdGraphRoute,
    AuthenticatedBooksBookIdIndexRoute: AuthenticatedBooksBookIdIndexRoute,
  }

const AuthenticatedBooksBookIdRouteRouteWithChildren =
  AuthenticatedBooksBookIdRouteRoute._addFileChildren(
    AuthenticatedBooksBookIdRouteRouteChildren,
  )

interface AuthenticatedBooksRouteRouteChildren {
  AuthenticatedBooksBookIdRouteRoute: typeof AuthenticatedBooksBookIdRouteRouteWithChildren
  AuthenticatedBooksListRoute: typeof AuthenticatedBooksListRoute
  AuthenticatedBooksNewRoute: typeof AuthenticatedBooksNewRoute
}

const AuthenticatedBooksRouteRouteChildren: AuthenticatedBooksRouteRouteChildren =
  {
    AuthenticatedBooksBookIdRouteRoute:
      AuthenticatedBooksBookIdRouteRouteWithChildren,
    AuthenticatedBooksListRoute: AuthenticatedBooksListRoute,
    AuthenticatedBooksNewRoute: AuthenticatedBooksNewRoute,
  }

const AuthenticatedBooksRouteRouteWithChildren =
  AuthenticatedBooksRouteRoute._addFileChildren(
    AuthenticatedBooksRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBooksRouteRoute: typeof AuthenticatedBooksRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBooksRouteRoute: AuthenticatedBooksRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
